# KCRW feed generator config.yaml

# The root URL of the KCRW website
# source_root: "https://www.kcrw.com/"
# source_root: "./tests/data/"
source_root: "http://localhost:8888/"

# # Extra sitemap files
# extra_sitemaps:
# - "sitemap.xml.gz"    # https://www.kcrw.com/sitemap.xml.gz
# - "sitemap-1.xml.gz"  # https://www.kcrw.com/sitemap-shows/music/sitemap-1.xml.gz
# - "sitemap-2.xml.gz"  # https://www.kcrw.com/sitemap-shows/music/sitemap-2.xml.gz

# The default HTTP timeout in seconds for requests
http_timeout: 10

# The source for  shows (e.g., 'sitemap' or 'feed')
source: "sitemap"

# Logging configuration
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: "[%(asctime)s.%(msecs)03d] %(levelname)s [%(name)s.%(module)s.%(funcName)s:%(lineno)d] %(message)s"
      datefmt: "%Y-%m-%dT%H:%M:%S%z"
    json:
      "()": "kcrw_feed.persistent_logger.JSONFormatter"
      fmt_keys:
        level: "levelname"
        timestamp: "timestamp"
        message: "message"
        logger: "name"
        module: "module"
        function: "funcName"
        filename: "filename"
        line: "lineno"
        thread_name: "threadName"
  handlers:
    stdout:
      class: "logging.StreamHandler"
      level: "INFO"
      formatter: "simple"
      stream: "ext://sys.stdout"
    file:
      class: "logging.handlers.RotatingFileHandler"
      level: "DEBUG"
      formatter: "json"
      filename: "./logs/kcrw_feed.jsonl"
      maxBytes: 10485760
      backupCount: 3
  loggers:
    root:
      level: "DEBUG"
      handlers: ["stdout", "file"]